// SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

import "@openzeppelin/contracts/access/Ownable.sol";

import "./lib/BrevisAppZkOnly.sol";

// Only accept ZK-attested results.
contract AddLiquidityZkOnly is BrevisAppZkOnly, Ownable {
    event LiquidityAmountAdded(uint64 blockNum, address LP, uint256 amount);

    bytes32 public vkHash;

    constructor(address _brevisRequest) BrevisAppZkOnly(_brevisRequest) Ownable(msg.sender) {}

    // BrevisQuery contract will call our callback once Brevis backend submits the proof.
    // This method is called with once the proof is verified.
    function handleProofResult(bytes32 _vkHash, bytes calldata _circuitOutput) internal override {
        // We need to check if the verifying key that Brevis used to verify the proof
        // generated by our circuit is indeed our designated verifying key. This proves
        // that the _circuitOutput is authentic
        require(vkHash == _vkHash, "invalid vk");
        (address LpAddr, uint64 blockNum, uint256 amount) = decodeOutput(_circuitOutput);
        emit LiquidityAmountAdded(blockNum, LpAddr, amount);
    }

    function decodeOutput(bytes calldata o) internal pure returns (address, uint64, uint256) {
        uint64 blockNum = uint64(bytes8(o[0:8]));
        address LpAddr = address(bytes20(o[8:28]));
        uint256 amount = uint256(bytes32(o[28:60]));
        return (LpAddr, blockNum, amount);
    }

    function setVkHash(bytes32 _vkHash) external onlyOwner {
        vkHash = _vkHash;
    }
}
